### ISSUE TITLE
一个报错，感觉是和这个模组有关

### ISSUE THREAD

**Issue by buptdancer** [AmarokIce/1.7.10-WithWolfMoon#1]
[minecraft-exported-crash-info-2024-08-22T19-37-17.zip](https://github.com/user-attachments/files/16709955/minecraft-exported-crash-info-2024-08-22T19-37-17.zip)
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: wolf/someoneice/manamoon/Config
Caused by: java.lang.NoClassDefFoundError: wolf/someoneice/manamoon/Config

**Comment by AmarokIce** [comment]
Moon Mana 模组很快会跟进 PPc 版本，在此之前倒退 PPc 版本可以解决这个问题。

这个问题不属于这个仓库，这份 Issue 将会被关闭。
